config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'users#index'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { minimum: 10,maximum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(name: params[:session][:name])
        #render plain: params[:session][:password].inspect
        if user && user.authenticate(params[:session][:password])
        # Log the user in and redirect to the user's show page.
        sessions[:user_id] = user.id
        flash[:success] = "Login success"
        redirect_to user  
        else
        # Create an error message.
        flash[:danger] = 'Invalid email/password combination' # Not quite right!
        render 'new'
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You are logged out"
        redirect_to login_path
    end

    private def user_name_params
        params.require(:user).permit(:name)
    end

    def match_password(login_password="")
        encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_param)

    if(@user.save)
      redirect_to @user
    else
      render 'new'
    end
  end

  def user_param
    params.require(:user).permit(:name, :password)
  end 

end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in user
        session[:user_id] = user.id
    end

    def log_out
        session.delete :user_id
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginApp</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/users/index.html.erb
<h1>List User</h1>
<% @users.each do |user| %>
    <h2><%= user.name %></h2>
    <p><%= user.password %></p>
<% end %>

app/views/users/new.html.erb
<h1>Add Users</h1>
<%= form_for :user, url: users_path do |f| %>
    <% if @user.errors.any? %>
        <% @user.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%=msg%></div>
        <% end %>
    <% end %>

    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :password %><br>
        <%= f.text_field :password %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left">
        <label><%= @user.name %></label>
      </div>
      <%= link_to "Logout", logout_path, method: :delete %> 
    </div>
  </div>
</div>